language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO=2.0
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pycodestyle --use-mirrors
  - pip install -q -e . --use-mirrors
before_script:
  - pycodestyle --exclude=migrations --max-line-length=120 --ignore=E731 datatableview
